# Software dependencies
name: laby-jupyter

channels:
- conda-forge

dependencies:
- notebook
- xeus-cling
- xwidgets
- pip
- matplotlib
- ipywidgets
- taits.api
- traitlets
- re
- os
- functool
- threading
- copy
- enum
- math
pip:
     - .
